### ISSUE TITLE
Adding standard iso8601 json decoder

### ISSUE THREAD

**Issue by JaapWijnen** [pointfreeco/swift-url-routing#23]
Some discussion is probably needed on how to best approach this. Today I ran into the issues of one of my routes not working when using swift-url-routing in combination with Vapor's testing capabilities. After some digging I found it was due to Vapor's JSONDecoder and encoder defaulting to a .iso8601 date decoding/encoding strategy. 
This means in our routers whenever we're using `Date` objects we'd have to inject custom json encoders and furthermore for first time users it's quite difficult to pinpoint where the issue originates from. 
Ideally we could do some kind of addition that lives in `vapor-routing` to not pollute this package too much with Vapor implementation details. But I'm not sure of what a good solution would be.

**Comment by stephencelis** [comment]
@JaapWijnen We have an idea of how to address this problem, but it unfortunately depends on some Swift 5.7 features to do it right.
