### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by kgrigsby59** [pointfreeco/swift-url-routing#34]
Getting error:
error: The package product 'XCTestDynamicOverlay' requires minimum platform version 13.0 for the iOS platform, but this target supports 9.0 (in target 'URLRouting' from project 'swift-url-routing')

I expect this is because XCTestDynamicOverlay was just updated with platform versions and this package doesn't have any.

**Comment by stephencelis** [comment]
@kgrigsby59 That's correct. We'll do some bump releases soon, but in the meantime you can lock your `xctest-dynamic-overlay` dependency manually. Sorry about that!
