### ISSUE TITLE
Typo in deprecation

### ISSUE THREAD

**Issue by dmzza** [pointfreeco/swift-url-routing#38]
https://github.com/pointfreeco/swift-url-routing/blob/380347731cd4c532696f27613fbdb12661ba8949/Sources/URLRouting/Internal/Deprecations.swift#L11

This line should be:
` @available(*, deprecated, renamed: "decodedResponse(for:as:decoder:)")`

**Comment by stephencelis** [comment]
@dmzza Good catch! Do you want to contribute a quick PR to fix?

**Comment by dmzza** [comment]
I would, but I'm contractually prohibited.
