### ISSUE TITLE
Additional HTTP Headers don't seems to be passe to the request

### ISSUE THREAD

**Issue by mackoj** [pointfreeco/swift-url-routing#4]
Hi,

Thanks for making this great lib as always !
When I try to pass a **Authorization** header to the session it is not passed to the request.

```swift
      let session = URLSession(configuration: .default)
      session.configuration.httpAdditionalHeaders = [
        "Authorization": "some token"
      ]
      let api = URLRoutingClient<TestRoute>.live(router: testRouter.baseURL("https://supersecretserver.com"), session: session)
```

I think the solution might be to add it to the request after creating it.
I will do a PR to explain it better.

**Comment by stephencelis** [comment]
@mackoj Thanks for taking the time to report!

According to Apple's [docs](https://developer.apple.com/documentation/foundation/urlsessionconfiguration/1411532-httpadditionalheaders):

> An [`URLSession`](https://developer.apple.com/documentation/foundation/urlsession) object is designed to handle various aspects of the HTTP protocol for you. As a result, you should not modify the following headers:
> - `Authorization`
> - …

If you need to modify headers like these directly on the request, is it possible for you to utilize the `baseRequestData` method on routers instead?

```swift
let api = URLRoutingClient<TestRoute>.live(
  router: testRouter.baseRequestData(
    scheme: "https",
    host: "supersecretserver.com",
    headers: ["authorization": ["some token"]]
  ),
  session: session
)
```

**Comment by mackoj** [comment]
Thanks I will try this instead.

**Comment by mackoj** [comment]
It is working like a charm. Thanks @stephencelis

**Comment by mackoj** [comment]
But still if someone use URLSessionConfiguration for other headers than the forbidden ones they are not passed.

**Comment by stephencelis** [comment]
@mackoj Are you sure? I think URLSession should try to apply those automatically (if not, it's unclear to me what the point of `httpAdditionalHeaders` is).

Regardless, you can always use `baseRequestData` to automatically apply certain headers to a request.
