### ISSUE TITLE
Can't parse a Route with String Path component 

### ISSUE THREAD

**Issue by rcasula** [pointfreeco/swift-url-routing#8]
Hi, I was trying to model an existing API with this library, but seems to me that it is not possibile to Model a Route with String Path components.

Example:

This is one of the urls: `BASE_URL/books/AUTHOR_NAME`.

And this is the modeled route:
```swift
enum SiteRoute {
    case books(author: String)
}
```
If I try to define the Router like this, it throws me a compile error. I can't figure out how i can  parse and construct another path component using String type instead of Double, Int, UUID....
```swift
let router = OneOf {
    Route(.case(SiteRoute.books)) {
        Path { "books" }
        Parse(.string) // ??
    }
}
```

How can I construct a Router that parses the Route above?

**Comment by davdroman** [comment]
Try:

```swift
let router = OneOf {
    Route(.case(SiteRoute.books)) {
        Path { "books"; Parse(.string) }
    }
}
```

**Comment by rcasula** [comment]
Oh wow, I couldn't see the obvious 🤦‍♂️ Thank you!
